### ISSUE TITLE
Remote repeating like a keyboard

### ISSUE THREAD

**Issue by Scramblejams** [graysky2/streamzap#5] opened 2020-12-27 11:48 UTC
Thanks for putting this together! Having an issue I hope you can help me solve.

I'm on OSMC 18.9.0 on a Raspberry Pi 3 B, using lirc 0.9.4 (OSMC's own package of it). I installed as per your instructions, went into My OSMC -> Remotes and selected the Streamzap conf. When I press a button the correct input is applied in the UI, then there's a pause (maybe half a second), then a repeated series of the same input at a constant interval. Feels exactly as if I were holding down a key on a keyboard and the key repeat function was going. I don't believe I'm seeing doubling, it seems like the remote is being interpreted as a keyboard with a long-held key.

I made sure the modules were blacklisted as instructed. lsmod looks like:

$ lsmod|grep -E "(stream|ir_)"
rc_streamzap           16384  0
streamzap              16384  0
gpio_ir_recv           16384  0
rc_core                49152  7 streamzap,rc_streamzap,gpio_ir_recv

$ ps auwx|grep -i irc
root       428  0.0  0.1   2060  1356 ?        Ss   03:40   0:00 /usr/sbin/eventlircd --evmap=/etc/eventlircd.d --socket=/var/run/lirc/lircd -f
root       450  0.0  0.1   4108  1428 ?        Ss   03:40   0:00 /usr/sbin/lircd --driver=default --device=/dev/lirc0 --uinput --output=/var/run/lirc/lircd-lirc0 --pidfile=/var/run/lirc/lircd-lirc0.pid /etc/lirc/lircd.conf
root       451  0.0  0.1   4108  1404 ?        Ss   03:40   0:00 /usr/sbin/lircd --driver=default --device=/dev/lirc1 --uinput --output=/var/run/lirc/lircd-lirc1 --pidfile=/var/run/lirc/lircd-lirc1.pid /etc/lirc/lircd.conf
root       538  0.0  0.3   8792  2692 ?        S    03:40   0:00 sudo -u osmc LIRC_SOCKET_PATH=/var/run/lirc/lircd /usr/lib/kodi/kodi.bin --standalone -fs

Not sure why OSMC is starting two lircd daemons up.

Anything else I can check?

Thanks.

**Comment by graysky2** [comment] 2020-12-27 12:05
No idea why you have two lircd running.  Conceptually that could be to blame, no?  Seem to fix that first I guess.  Does OSMC use systemd?

I have seen key doubling before but I believe it was due to the actual config.  I noted this in my readme.  Did you follow these steps: https://github.com/graysky2/streamzap#setup-lirc

**Comment by StagnationPoint** [comment] 2020-12-27 22:16
I looked into why I have two running, and it looks okay. It's because OSMC's eventlircd systemd service file starts one instance for each /dev/lirc* device:

ExecStartPost = /bin/sh -c "for f in /var/run/lirc/lircd-*.sh; do if [ -e $f ]; then s=$(basename $f .sh | sed 's/lircd-//g'); systemctl start lircd_helper@$s; fi; done"

In dmesg I see:

[    7.274381] rc rc0: lirc_dev: driver gpio_ir_recv registered at minor = 0, raw IR receiver, no transmitter
[    7.543535] rc rc1: lirc_dev: driver streamzap registered at minor = 1, raw IR receiver, no transmitter

I don't have anything hooked up to the GPIO pins, so I assume that second instance is harmless. I tried killing the one pointed at GPIO, and it made no difference. Killing the other one just stopped my Streamzap's inputs from coming through.

Yes, I did follow your steps, the modules are blacklisted and I verified after a reboot that any modules that were blacklisted are no longer loading.

I really don't believe this is doubling. I've experienced that before, and this isn't it. This looks exactly like when you hold down a key on the keyboard and that gives you an immediate input, then a pause, then a series of evenly timed repeat inputs. So I think something is still treating my remote as a keyboard, and an input as some kind of long press.

Thanks.

**Comment by Scramblejams** [comment] 2020-12-27 22:17
I looked into why I have two running, and it looks okay. It's because OSMC's eventlircd systemd service file starts one instance for each /dev/lirc* device:

ExecStartPost = /bin/sh -c "for f in /var/run/lirc/lircd-*.sh; do if [ -e $f ]; then s=$(basename $f .sh | sed 's/lircd-//g'); systemctl start lircd_helper@$s; fi; done"

In dmesg I see:

[ 7.274381] rc rc0: lirc_dev: driver gpio_ir_recv registered at minor = 0, raw IR receiver, no transmitter
[ 7.543535] rc rc1: lirc_dev: driver streamzap registered at minor = 1, raw IR receiver, no transmitter

I don't have anything hooked up to the GPIO pins, so I assume that second instance is harmless. I tried killing the one pointed at GPIO, and it made no difference. Killing the other one just stopped my Streamzap's inputs from coming through.

Yes, I did follow your steps, the modules are blacklisted and I verified after a reboot that any modules that were blacklisted are no longer loading.

I really don't believe this is doubling. I've experienced that before, and this isn't it. This looks exactly like when you hold down a key on the keyboard and that gives you an immediate input, then a pause, then a series of evenly timed repeat inputs. So I think something is still treating my remote as a keyboard, and an input as some kind of long press.

Thanks.

**Comment by graysky2** [comment] 2020-12-27 23:20
The module blacklist should take care of that.  You can test it by stopping lircd and seeing if the remote presses translate into keys.

**Comment by Scramblejams** [comment] 2020-12-28 07:02
This was a years-old installation (the remote worked fine until I updated the OSMC install sometime in the fall, then it broke), so I created a fresh one and followed your installation instructions. The issue persists.

Can you tell me what command you'd like me to run and what I'm looking for?

Thank you!

**Comment by graysky2** [comment] 2020-12-28 09:02
I don't have any undocumented steps into this honestly.  If you followed the steps I outlined, it should work.  I do not know OSMC.  I would start by going back to first principals.  Does raw lirc work? Stop kodi and test it on the shell.

Some references:
https://wiki.archlinux.org/index.php/LIRC/Quick_start_guide
https://wiki.archlinux.org/index.php/LIRC

Most the Arch wiki is based off upstream docs:
https://www.lirc.org/html/configuration-guide.html
http://lirc.sourceforge.net/lirc.org/html/index.html

**Comment by StagnationPoint** [comment] 2021-01-01 00:05
Thanks for your response. I ran out of time to troubleshoot this so I ordered an official OSMC remote and it worked fine. Unfortunate that I didn't track down the root cause but you can close this.

Thanks!

**Comment by Scramblejams** [comment] 2021-01-01 00:06
Thanks for your response. I ran out of time to troubleshoot this so I ordered an official OSMC remote and it worked fine. Unfortunate that I didn't track down the root cause but you can close this.

Thanks!

**Closed as completed** 2021-01-01 11:29 UTC
